# Classes
module DSLCompose
  class Interpreter
    class Execution
      attr_reader dsl: DSL
      attr_reader klass: Object
      attr_reader method_calls: MethodCalls
      attr_reader arguments: Arguments

      def initialize: (Object klass, DSL dsl, *untyped args) -> void
      def instance_eval: () -> void

      private
      def method_missing: (Symbol method_name, *untyped args) -> untyped
      def respond_to_missing?: (Symbol method_name, *untyped args) -> untyped

      class MethodIsUniqueError < StandardError
      end

      class RequiredMethodNotCalledError < StandardError
      end
    end
  end
end
