# Classes
module DSLCompose
  class DSL
    class DSLMethod
      class Argument
        class FormatValidation
          @regex: Regexp

          def initialize: (Regexp regex) -> void
          def validate: (String value) -> bool
        end
      end
    end
  end
end
