# Classes
module DSLCompose
  class ClassCoerce
    @class_name: String

    def initialize: (String class_name) -> void
    def to_class: -> untyped


    class UnexpectedClassNameError < StandardError
    end

  end
end
