# Classes
module DSLCompose
  class Parser
    self.@runs: untyped

    def initialize: -> void
    def self.for_children_of: (singleton(Object) base_class, ?final_children_only: bool, ?rerun: bool) -> void

    class NotInitializable < StandardError
    end
  end
end
