# Classes
module DSLCompose
  class Parser
    self.@runs: Array[{base_class: ::Object, block: untyped}]

    def initialize: -> void
    def self.for_children_of: (Object base_class, ?bool rerun) -> void

    class NotInitializable < StandardError
    end
  end
end
