# Classes
module DSLCompose
  class Interpreter
    class Execution
      class Arguments
        attr_reader arguments: Hash[untyped, untyped]
        attr_reader called_from: String

        def initialize: (untyped arguments, String called_from, *untyped args) -> void
        def to_h: -> Hash[untyped, untyped]

        class MissingRequiredArgumentsError < InterpreterError
        end

        class TooManyArgumentsError < InterpreterError
        end

        class OptionalArgumentsShouldBeHashError < InterpreterError
        end

        class InvalidArgumentTypeError < InterpreterError
        end

        class ArrayNotValidError < InterpreterError
        end
      end
    end
  end
end
