# Classes
module DSLCompose
  class Parser
    class ForChildrenOfParser
      class ForDSLParser
        @base_class: singleton(Object)
        @child_class: singleton(Object)
        @dsl_names: Array[Symbol]
        @dsl_execution: Interpreter::Execution

        def initialize: (singleton(Object) base_class, singleton(Object) child_class, Array[Symbol] dsl_names, bool on_current_class, bool on_ancestor_class) -> void

        # overriding this method because steep doesn't
        # correctly infer that a block is being passed to this method
        def instance_exec: (
          ::Hash[untyped, untyped] args
        ) -> void

        private
        def for_method: (Array[Symbol] method_names) -> void

        class AllBlockParametersMustBeKeywordParametersError < StandardError
        end

        class NoBlockProvided < StandardError
        end

        class DSLDoesNotExistError < StandardError
        end

        class DSLNamesShouldBeSymbolsError < StandardError
        end
      end
    end
  end
end
