# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class FormatValidation
          @regex: Regexp

          def initialize: (Regexp regex) -> void
          def validate!: (String value) -> true

          class InvalidValueError < StandardError
          end

          class ValidationFailedError < StandardError
          end

        end
      end
    end
  end
end