# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class IsAValidation
          @value: Object

          def initialize: (Object value) -> void
          def validate!: (untyped value) -> true

          class ValidationFailedError < StandardError
          end
        end
      end
    end
  end
end
