# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class LengthValidation
          @maximum: nil | Numeric
          @minimum: nil | Numeric
          @is: nil | Numeric

          def initialize: (?maximum: nil | Numeric, ?minimum: nil | Numeric, ?is: nil | Numeric) -> void
          def validate!: (String | Symbol value) -> true

          class ValidationFailedError < StandardError
          end

        end
      end
    end
  end
end