# TypeProf 0.21.7

# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class NotEndWithValidation
          @value: String

          def initialize: (String value) -> void
          def validate!: (String value) -> true

          class InvalidValueError < StandardError
          end

          class ValidationFailedError < StandardError
          end
        end
      end
    end
  end
end
