# TypeProf 0.21.7

# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class NotStartWithValidation
          @values: Array[Symbol]

          def initialize: (Symbol | Array[Symbol]) -> void
          def validate!: (Symbol | String value) -> true

          class InvalidValueError < StandardError
          end

          class ValidationFailedError < StandardError
          end
        end
      end
    end
  end
end
