# Classes
module DSLCompose
  class DSL
    class Arguments
      class Argument
        class StartWithValidation
          @values: Array[Symbol]

          def initialize: (Symbol | Array[Symbol] | String | Array[String]) -> void
          def validate!: (Symbol | String value) -> true

          class InvalidValueError < StandardError
          end

          class ValidationFailedError < StandardError
          end
        end
      end
    end
  end
end
