# Classes
module DSLCompose
  class Interpreter
    class Execution
      class MethodCalls
        class MethodCall
          @method_call: MethodCall
          @parser_usage_notes: Array[String]

          attr_reader dsl_method: DSL::DSLMethod
          attr_reader arguments: Arguments

          def initialize: (DSL::DSLMethod dsl_method, *untyped args) -> void
          def method_name: -> Symbol
          def to_h: -> Hash[untyped, untyped]
        end
      end
    end
  end
end
