# Classes
module DSLCompose
  class Interpreter
    class Execution
      class MethodCalls
        class MethodCall
          @dsl_method: DSL::DSLMethod
          @arguments: Arguments

          def initialize: (DSL::DSLMethod dsl_method, *untyped args) -> void
          def method_name: -> Symbol
        end
      end
    end
  end
end
