# Classes
module DSLCompose
  class DSL
    class Arguments
      @arguments: Hash[Symbol, Argument]

      def initialize: -> void
      def arguments: -> Array[Argument]
      def optional_arguments: -> Array[Argument]
      def required_arguments: -> Array[Argument]
      def argument: (Symbol name) -> Argument
      def optional_argument: (Symbol name) -> Argument
      def required_argument: (Symbol name) -> Argument
      def has_argument?: (Symbol name) -> bool
      def add_argument: (Symbol name, bool required, bool kwarg, argument_type `type`, ?array: bool) -> Argument

      class ArgumentDoesNotExistError < StandardError
        end

      class ArgumentOrderingError < StandardError
        end

      class ArgumentAlreadyExistsError < StandardError
        end

      class RequestedOptionalArgumentIsRequiredError < StandardError
        end

      class RequestedRequiredArgumentIsOptionalError < StandardError
        end
    end
  end
end
