# Classes
module DSLCompose
  class DSL
    class DSLMethod

      attr_reader name: Symbol
      attr_reader unique: bool
      attr_reader required: bool
      attr_reader description: String
      attr_reader arguments: Arguments

      def initialize: (Symbol name, bool unique, bool required) -> void
      def set_description: (String description) -> void
      def has_description?: -> bool
      def unique?: -> bool
      def required?: -> bool
      def optional?: -> bool

      class ArgumentDoesNotExistError < StandardError
        end

      class InvalidNameError < StandardError
        end

      class MethodNameIsReservedError < StandardError
        end

      class InvalidDescriptionError < StandardError
        end

      class DescriptionAlreadyExistsError < StandardError
        end

      class ArgumentOrderingError < StandardError
        end

      class ArgumentAlreadyExistsError < StandardError
        end

      class RequestedOptionalArgumentIsRequiredError < StandardError
        end

      class RequestedRequiredArgumentIsOptionalError < StandardError
        end
    end
  end
end