name: Linter

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@v3

      # Setup ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      # Bundle install
      - run: bundle install

      # run the linter
      - name: Run standard linter
        run: bundle exec standardrb
